#include "stm32f446xx.h"
#include "Timer.h"

void initSPI(void);
void initClocks(void);
void configSPI1Pins(void);
void setPinMode(void);
void setAlternateFunction(void);
void configSPI(void);
uint8_t transferSPI(uint8_t tx_data);

void initClocks(void){
    //
    // Clock initialization is required to enable peripheral hardware blocks:
    // - GPIO ports (GPIOA and GPIOB)
    // - SPI1 peripheral
    //

    // Enable clocks for GPIO ports (AHB1 peripheral bus)
    RCC->AHB1ENR |= ((1u << 0)       // Enable GPIOA clock
                    |(1u << 1));     // Enable GPIOB clock

    // Enable clock for SPI1 peripheral (APB2 peripheral bus)
    RCC->APB2ENR |= (1u << 12);      // SPI1 clock enabled (bit 12)
}

void configSPI(void){
	// Clear Bits
	SPI1->CR1 &= ~(
	              (1 << 15)  // BIDIMODE: Set Full Duplex mode (0 = Full Duplex, 1 = Half Duplex)
	             |(1 << 13)  // CRCEN: Disable CRC (0 = CRC Calculation Disabled)
				 |(1 << 11)	 // DFF: clear
	             |(1 << 10)  // RXONLY: Disable Simplex mode (0 = Full Duplex)
	             |(1 << 9)   // SSM: Disable Software Slave Management (0 = Hardware NSS management)
	             |(1 << 7)   // LSBFIRST: MSB first (0 = MSB first, 1 = LSB first)
	             |(7 << 3)   // BR[2:0]: Clear baud rate control bits (used for SPI clock speed division)
	             );
	SPI1->CR2 &= ~(
            	  (7 << 5)	 // Clear Interrupt Bits
				 |(1 << 4) 	 // SPI in Motorola format
				 |(1 << 3) 	 // No consecutive transfer
				 |(3 << 0)	 // No DMA
				 );
	// Set Bits
	SPI1->CR1 |= (
				  (1 << 11)	 // DFF: 16 bit data transfer option
	             |(5 << 3)   // BR[2:0]: Set SPI clock prescaler to divide by 64
	             |(1 << 2)   // MSTR: Enable Master mode
	             |(1 << 1)   // CPOL: Set Clock Polarity to 1 (Idle high)
	             |(1 << 0)   // CPHA: Set Clock Phase to 1 (Capture on second clock transition)
	             );
	SPI1->CR2 |= ((1 << 2)); // SSOE enabled

}

void setPinMode(void){
    //
    // Setting up SPI1 requires configuring specific pins to Alternate Function mode:
    //
    // PA4  - SPI1 SSEL (Chip Select - Active Low)
    // PA6  - SPI1 MISO (Master In Slave Out - Data received by Master)
    // PA7  - SPI1 MOSI (Master Out Slave In - Data sent by Master)
    // PB3  - SPI1 SCLK (SPI Clock generated by Master)
    //

    // RESET PIN MODES: First clear the existing pin mode configuration
    GPIOA->MODER &= ~(
    				 (3 << (2 * 4))   // Clear bits [9:8]   for PA4
                    |(3 << (2 * 6))   // Clear bits [13:12] for PA6
                    |(3 << (2 * 7))   // Clear bits [15:14] for PA7
                    );
    GPIOB->MODER &= ~(3 << (2 * 3));   // Clear bits [7:6] for PB3

    // CONFIGURE PIN MODES: Set pins to Alternate Function (AF) mode (binary '10')
    GPIOA->MODER |= (
    				 (2 << (2 * 4))    // Set PA4 (SSEL) to AF mode
                    |(2 << (2 * 6))    // Set PA6 (MISO) to AF mode
                    |(2 << (2 * 7))    // Set PA7 (MOSI) to AF mode
                    );
    GPIOB->MODER |= (2 << (2 * 3));    // Set PB3 (SCLK) to AF mode
}

void setAlternateFunction(void){
    //
    // Configuring Alternate Function (AF) for SPI1:
    //
    // PA4  - SPI1 SSEL (Chip Select - Active Low)   -> AF5
    // PA6  - SPI1 MISO (Master In Slave Out)        -> AF5
    // PA7  - SPI1 MOSI (Master Out Slave In)        -> AF5
    // PB3  - SPI1 SCLK (Clock Signal)               -> AF5
    //

    // RESET ALTERNATE FUNCTION SETTINGS:
    // Each pin's alternate function is configured using 4-bit fields in the AFR register.
    // Clearing these bits ensures we start with a clean state before setting the desired AF.
    GPIOA->AFR[0] &= ~(
                         (0xF << (4 * 4))   // Clear 4 bits for PA4 (AFR[0] controls pins 0-7)
                        |(0xF << (4 * 6))   // Clear 4 bits for PA6
                        |(0xF << (4 * 7))   // Clear 4 bits for PA7
                        );
    GPIOB->AFR[0] &= ~(0xF << (4 * 3));   // Clear 4 bits for PB3

    // CONFIGURE ALTERNATE FUNCTION (AF5) FOR SPI1:
    // AF5 (binary 0101, decimal 5) is the alternate function used for SPI1.
    GPIOA->AFR[0] |= (
                         (5 << (4 * 4))   // Set PA4 to AF5 (SPI1_SSEL)
                        |(5 << (4 * 6))   // Set PA6 to AF5 (SPI1_MISO)
                        |(5 << (4 * 7))   // Set PA7 to AF5 (SPI1_MOSI)
                        );
    GPIOB->AFR[0] |= (5 << (4 * 3));   // Set PB3 to AF5 (SPI1_SCLK)
}


void initSPI(void){

}
